CREATE TABLE Department (
id SERIAL PRIMARY KEY,
name VARCHAR(30) NOT NULL
);

CREATE TABLE Role (
id SERIAL PRIMARY KEY,
title VARCHAR(30) NOT NULL,
salary DECIMAL NOT NULL,
department_id INTEGER NOT NULL,
FOREIGN KEY (department_id)
REFERENCES Department(id)
);

CREATE TABLE Employee(
id SERIAL PRIMARY KEY,
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR(30) NOT NULL,
role_id INTEGER NOT NULL,
FOREIGN KEY (role_id)
REFERENCES Role(id),
manager_id INTEGER NOT NULL,
FOREIGN KEY (manager_id)
REFERENCES Employee(id)
);